name: Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - uses: retypeapp/action-build@v3
        id: build
        with:
          config: ./

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ steps.build.outputs.retype-output-path }} --project-name=bloom-docs --branch=retype
